config/routes.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

Diaspora::Application.routes.draw do
  if Rails.env.production?
    mount RailsAdmin::Engine => '/admin_panel', :as => 'rails_admin'
  end


  get "/atom.xml" => redirect('http://blog.diasporafoundation.org/feed/atom') #too many stupid redirects :()
  
  get 'oembed' => 'posts#oembed', :as => 'oembed'
  # Posting and Reading
  resources :reshares

  resources :status_messages, :only => [:new, :create]

  resources :posts do
    member do
      get :next
      get :previous
      get :interactions
    end

    resources :likes, :only => [:create, :destroy, :index ]
    resources :participations, :only => [:create, :destroy, :index]
    resources :comments, :only => [:new, :create, :destroy, :index]
  end

  match "/framer" => redirect("/posts/new")

  get 'p/:id' => 'posts#show', :as => 'short_post'
  get 'posts/:id/iframe' => 'posts#iframe', :as => 'iframe'

  # roll up likes into a nested resource above
  resources :comments, :only => [:create, :destroy] do
    resources :likes, :only => [:create, :destroy, :index]
  end

  # Streams
  get "participate" => "streams#activity", :as => "activity_stream" # legacy
  get "explore" => "streams#multi", :as => "stream"                 # legacy

  get "activity" => "streams#activity", :as => "activity_stream"
  get "stream" => "streams#multi", :as => "stream"
  get "public" => "streams#public", :as => "public_stream"
  get "followed_tags" => "streams#followed_tags", :as => "followed_tags_stream"
  get "mentions" => "streams#mentioned", :as => "mentioned_stream"
  get "liked" => "streams#liked", :as => "liked_stream"
  get "commented" => "streams#commented", :as => "commented_stream"
  get "aspects" => "streams#aspects", :as => "aspects_stream"
  
  resources :aspects do
    put :toggle_contact_visibility
  end

  get 'bookmarklet' => 'status_messages#bookmarklet'
  get 'new_bookmarklet' => 'status_messages#new_bookmarklet'

  resources :photos, :except => [:index] do
    put :make_profile_photo
  end

  post "upload_wallpaper" => 'profiles#upload_wallpaper_image'

  # ActivityStreams routes
  scope "/activity_streams", :module => "activity_streams", :as => "activity_streams" do
    resources :photos, :controller => "photos", :only => [:create]
  end

  resources :conversations do
    resources :messages, :only => [:create, :show]
    delete 'visibility' => 'conversation_visibilities#destroy'
  end

  get 'notifications/read_all' => 'notifications#read_all'
  resources :notifications, :only => [:index, :update] do
  end

  resources :tags, :only => [:index]
  scope "tags/:name" do
    post   "tag_followings" => "tag_followings#create", :as => 'tag_tag_followings'
    delete "tag_followings" => "tag_followings#destroy", :as => 'tag_tag_followings'
  end

  post   "multiple_tag_followings" => "tag_followings#create_multiple", :as => 'multiple_tag_followings'
  resources "tag_followings", :only => [:create]

  get 'tags/:name' => 'tags#show', :as => 'tag'

  resources :apps, :only => [:show]

  #Cubbies info page

  resource :token, :only => :show

  # Users and people

  resource :user, :only => [:edit, :update, :destroy], :shallow => true do
    get :getting_started_completed
    get :export
    get :export_photos
  end

  controller :users do
    get 'public/:username'          => :public,           :as => 'users_public'
    match 'getting_started'         => :getting_started,  :as => 'getting_started'
    match 'privacy'                 => :privacy_settings, :as => 'privacy_settings'
    get 'getting_started_completed' => :getting_started_completed
    get 'confirm_email/:token'      => :confirm_email,    :as => 'confirm_email'
  end

  # This is a hack to overide a route created by devise.
  # I couldn't find anything in devise to skip that route, see Bug #961
  match 'users/edit' => redirect('/user/edit')

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :password      => "devise/passwords",
                                      :sessions      => "sessions"}

  #legacy routes to support old invite routes
  get 'users/invitation/accept' => 'invitations#edit'
  get 'invitations/email' => 'invitations#email', :as => 'invite_email'
  get 'users/invitations' => 'invitations#new', :as => 'new_user_invitation'
  post 'users/invitations' => 'invitations#create', :as => 'new_user_invitation'
  
  get 'login' => redirect('/users/sign_in')

  scope 'admins', :controller => :admins do
    match :user_search
    get   :admin_inviter
    get   :weekly_user_stats
    get   :correlations
    get   :stats, :as => 'pod_stats'
    get   "add_invites/:invite_code_id" => 'admins#add_invites', :as => 'add_invites'
  end

  resource :profile, :only => [:edit, :update]
  resources :profiles, :only => [:show]


  resources :contacts,           :except => [:update, :create] do
    get :sharing, :on => :collection
  end
  resources :aspect_memberships, :only  => [:destroy, :create]
  resources :share_visibilities,  :only => [:update]
  resources :blocks, :only => [:create, :destroy]

  get 'i/:id' => 'invitation_codes#show', :as => 'invite_code'

  get 'people/refresh_search' => "people#refresh_search"
  resources :people, :except => [:edit, :update] do
    resources :status_messages
    resources :photos
    get :contacts
    get "aspect_membership_button" => :aspect_membership_dropdown, :as => "aspect_membership_button"

    member do
      get :last_post
    end

    collection do
      post 'by_handle' => :retrieve_remote, :as => 'person_by_handle'
      get :tag_index
    end
  end
  get '/u/:username' => 'people#show', :as => 'user_profile'
  get '/u/:username/profile_photo' => 'users#user_photo'


  # Federation

  controller :publics do
    get 'webfinger'             => :webfinger
    get 'hcard/users/:guid'     => :hcard
    get '.well-known/host-meta' => :host_meta
    post 'receive/users/:guid'  => :receive
    post 'receive/public'       => :receive_public
    get 'hub'                   => :hub
  end



  # External

  resources :authorizations, :only => [:index, :destroy]
  scope "/oauth", :controller => :authorizations, :as => "oauth" do
    get "authorize" => :new
    post "authorize" => :create
    post :token
  end

  resources :services, :only => [:index, :destroy]
  controller :services do
    scope "/auth", :as => "auth" do
      match ':provider/callback' => :create
      match :failure
    end
    scope 'services' do
      match 'inviter/:provider' => :inviter, :as => 'service_inviter'
      match 'finder/:provider'  => :finder,  :as => 'friend_finder'
    end
  end

  scope 'api/v0', :controller => :apis do
    get :me
  end

  namespace :api do
    namespace :v0 do
      get "/users/:username" => 'users#show', :as => 'user'
      get "/tags/:name" => 'tags#show', :as => 'tag'
    end
  end

  get 'community_spotlight' => "contacts#spotlight", :as => 'community_spotlight'
  # Mobile site

  get 'mobile/toggle', :to => 'home#toggle_mobile', :as => 'toggle_mobile'

  #Protocol Url
  get 'protocol' => redirect("https://github.com/diaspora/diaspora/wiki/Diaspora%27s-federation-protocol")

  # Resque web
  if AppConfig[:mount_resque_web]
    mount Resque::Server.new, :at => '/resque-jobs', :as => "resque_web"
  end

  # Startpage
  root :to => 'home#show'
end

app/models/contact.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class Contact < ActiveRecord::Base
  belongs_to :user

  belongs_to :person
  validates :person, :presence => true

  has_many :aspect_memberships
  has_many :aspects, :through => :aspect_memberships

  has_many :share_visibilities, :source => :shareable, :source_type => 'Post'
  has_many :posts, :through => :share_visibilities, :source => :shareable, :source_type => 'Post'

  validate :not_contact_for_self,
           :not_blocked_user,
           :not_contact_with_closed_account

  validates_presence_of :user
  validates_uniqueness_of :person_id, :scope => :user_id

  before_destroy :destroy_notifications

  scope :all_contacts_of_person, lambda {|x| where(:person_id => x.id)}

    # contact.sharing is true when contact.person is sharing with contact.user
  scope :sharing, lambda {
    where(:sharing => true)
  }

  # contact.receiving is true when contact.user is sharing with contact.person
  scope :receiving, lambda {
    where(:receiving => true)
  }

  scope :for_a_stream, lambda {
    includes(:aspects, :person => :profile).
        order('profiles.last_name ASC')
  }

  scope :only_sharing, lambda {
    sharing.where(:receiving => false)
  }

  def destroy_notifications
    Notification.where(:target_type => "Person",
                       :target_id => person_id,
                       :recipient_id => user_id,
                       :type => "Notifications::StartedSharing").delete_all
  end

  def dispatch_request
    request = self.generate_request
    Postzord::Dispatcher.build(self.user, request).post
    request
  end

  def generate_request
    Request.diaspora_initialize(:from => self.user.person,
                :to => self.person,
                :into => aspects.first)
  end

  def receive_shareable(shareable)
    ShareVisibility.create!(:shareable_id => shareable.id, :shareable_type => shareable.class.base_class.to_s, :contact_id => self.id)
  end

  def contacts
    people = Person.arel_table
    incoming_aspects = Aspect.where(
      :user_id => self.person.owner_id,
      :contacts_visible => true).joins(:contacts).where(
        :contacts => {:person_id => self.user.person.id}).select('aspects.id')
    incoming_aspect_ids = incoming_aspects.map{|a| a.id}
    similar_contacts = Person.joins(:contacts => :aspect_memberships).where(
      :aspect_memberships => {:aspect_id => incoming_aspect_ids}).where(people[:id].not_eq(self.user.person.id)).select('DISTINCT people.*')
  end

  def mutual?
    self.sharing && self.receiving
  end

  def in_aspect? aspect
    if aspect_memberships.loaded?
      aspect_memberships.detect{ |am| am.aspect_id == aspect.id }
    elsif aspects.loaded?
      aspects.detect{ |a| a.id == aspect.id }
    else
      AspectMembership.exists?(:contact_id => self.id, :aspect_id => aspect.id)
    end
  end

  private
  def not_contact_with_closed_account
    if person_id && person.closed_account?
      errors[:base] << 'Cannot be in contact with a closed account'
    end
  end

  def not_contact_for_self
    if person_id && person.owner == user
      errors[:base] << 'Cannot create self-contact'
    end
  end

  def not_blocked_user
    if user && user.blocks.where(:person_id => person_id).exists?
      errors[:base] << 'Cannot connect to an ignored user'
      false
    else
      true
    end
  end
end

app/views/shared/_add_remove_services.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


%ul.stream#service_stream
  - if @services.count > 0
    - for service in @services
      %h3
        %b= service.provider
        = t('services.index.logged_in_as')
        %b= service.nickname
        = link_to t('services.index.disconnect'), service_path(service), :data => { :confirm => t('services.index.really_disconnect', :service => service.provider) }, :method => :delete
  - else
    = t('services.index.no_services')

- AppConfig.configured_services.each do |service|
  - unless @services.any?{|x| x.provider == service}
    %h4= link_to t("services.index.connect_to_#{service}"), "#", :onclick => "window.open('/auth/#{service}', 'popup', 'height=400,width=500')"

app/views/shared/_aspect_dropdown.html.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.dropdown{:class => ["hang_#{hang}", defined?(dropdown_class) && dropdown_class]}
  .button.toggle{:class => ("in_aspects" if selected_aspects.size > 0)}
    - if selected_aspects.size == all_aspects.size
      = t('all_aspects')
    - elsif selected_aspects.size == 1
      = selected_aspects.first.name
    - else
      = t('.toggle', :count => selected_aspects.size)
    &#9660;

  .wrapper
    %ul.dropdown_list{:unSelectable => 'on', 'data-person_id' => (person.id if defined?(person) && person), 'data-service_uid' => (service_uid if defined?(service_uid)), 'data-person-short-name' => (person.first_name if defined?(person) && person)}
      - for aspect in all_aspects
        = aspect_dropdown_list_item(aspect, selected_aspects.include?(aspect) )

      - if (dropdown_may_create_new_aspect && defined?(person) && person)
        %li.newItem
          .add_aspect
            = link_to t('contacts.index.add_a_new_aspect'), new_aspect_path(:person_id => person.id, :remote => true), :rel => 'facebox'

app/views/shared/_author_info.html.haml
#author_info.show
  = person_image_link(person)
  .from
    %h5
      = person.name

    #person_nav_links
      = link_to t('layouts.header.profile'), local_or_remote_person_path(person)
      = link_to t('_photos'), person_photos_path(person)

app/views/shared/_contact_list.html.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


.contact_list_controls
  = search_field_tag :contact_search, "", :id => "contact_list_search", :class => 'contact_list_search', :results => 5, :placeholder => t('.all_contacts')
  = t('contacts', :count =>@aspect_contacts_count)

.contact_list.searchable
  %ul.contacts
    - for contact in contacts
      %li.contact{:data=>{:contact_id=>contact.id}}
        = person_image_tag contact.person
        %h4.name
          = link_to contact.person.name, contact.person
        .right
          = aspect_membership_button(aspect, contact, contact.person)

app/views/shared/_contact_sidebar.html.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.span-5.append-1
  = render 'contacts/aspect_listings'

  %hr

  %ul.left_nav
    - if AppConfig[:community_spotlight]
      %li{:class => ("active" if @spotlight)}
        = link_to t('contacts.spotlight.community_spotlight'), community_spotlight_path, :class => "element_selector"

app/views/shared/_donatediaspora.html.haml
%form{:action => "https://diaspora-project-site.heroku.com/donate", :method => "get"}
  %select{:name => "monthly_amount"}
    %option{:value => "1"} Supporter : $5.00USD
    %option{:value => "2"} Member : $10.00USD
    %option{:value => "3"} Freedom Fighter : $20.00USD
  %input{:name => "submit", :type => "submit", :value => t('aspects.index.donate')}

app/views/shared/_invitations.haml
= t('.share_this')
= invite_link(current_user.invitation_code)
= link_to t('.by_email'), new_user_invitation_path, :title => t('.invite_someone'), :rel => 'facebox'

app/views/shared/_post_info.mobile.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.from
  = person_image_link(post.author, :size => :thumb_small)
  = person_link(post.author)
  .info
    %span.time{:integer => post.created_at.to_i}
      = t('ago', :time => time_ago_in_words(post.created_at))
    %span.via
      - if post.activity_streams?
        = t('shared.stream_element.via', :link => link_to("#{post.provider_display_name}", post.actor_url)).html_safe
      - elsif post.provider_display_name == 'mobile'
        = t('shared.stream_element.via_mobile', :link => nil)
    &ndash;
    %span.scope_scope
      - if post.public?
        = t('public')
      - else
        = t('limited')

app/views/shared/_publisher.html.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

-if publisher_explain
  :javascript
    $(document).ready(function() {
        Publisher.triggerGettingStarted();
      });

#publisher{:class => ((aspect == :profile || publisher_open) ? "mention_popup" : "closed")}
  .content_creation
    = form_for(StatusMessage.new) do |status|
      = status.error_messages
      %div
        %params
          #publisher_textarea_wrapper
            = link_to( image_tag('deletelabel.png'), "#", :id => "hide_publisher", :title => t('.discard_post'))
            %ul#photodropzone
            - if current_user.getting_started?
              = status.text_area :fake_text, :rows => 2, :value => h(publisher_formatted_text), :tabindex => 1, :placeholder => "#{t('contacts.index.start_a_conversation')}...",
                :title => popover_with_close_html( '1. ' + t('shared.public_explain.share') ),
                'data-content' => t('shared.public_explain.new_user_welcome_message')
            - else
              = status.text_area :fake_text, :rows => 2, :value => h(publisher_formatted_text), :tabindex => 1, :placeholder => "#{t('contacts.index.start_a_conversation')}..."
            = status.hidden_field :text, :value => h(publisher_hidden_text), :class => 'clear_on_submit'

            #file-upload{:title => t('.upload_photos')}
              = image_tag 'icons/camera.png', :alt => t('.upload_photos').titleize

      - if publisher_public
        = hidden_field_tag 'aspect_ids[]', "public"
      - elsif all_aspects_selected?(selected_aspects)
        = hidden_field_tag 'aspect_ids[]', "all_aspects"
      - else
        - for aspect_id in aspect_ids
          = hidden_field_tag 'aspect_ids[]', aspect_id.to_s

      .options_and_submit
        .public_toggle
          %span#publisher_service_icons
            - if current_user.services
              - for service in current_user.services
                = image_tag "social_media_logos/#{service.provider}-16x16.png", :title => service.provider.titleize, :class => "service_icon dim", :id =>"#{service.provider}", :maxchar => "#{service.class::MAX_CHARACTERS}"
            = link_to (image_tag "icons/monotone_wrench_settings.png"), "#question_mark_pane", :class => 'question_mark', :rel => 'facebox', :title => t('shared.public_explain.manage')

          .dropdown{ ! current_user.getting_started? ? {:class => "hang_right"} : { :class => "hang_right", :title => popover_with_close_html("2. #{t('shared.public_explain.control_your_audience')}"), 'data-content'=> t('shared.public_explain.visibility_dropdown')} }
            .button.toggle.publisher
              - if publisher_public
                = t('public')
              - elsif all_aspects_selected?(selected_aspects)
                = t('all_aspects')
              - elsif selected_aspects.size == 1
                = selected_aspects.first.name
              - else
                = t('shared.aspect_dropdown.toggle', :count => selected_aspects.size)
              &#9660;

            .wrapper
              %ul.dropdown_list{:unSelectable => 'on', 'data-person_id' => (person.id if defined?(person) && person), 'data-service_uid' => (service_uid if defined?(service_uid))}
                %li.public.radio{"data-aspect_id" => "public", :class => ("selected" if publisher_public)}
                  = t('public')

                %li.divider.all_aspects.radio{:style => "border-bottom: 1px solid #ddd;", "data-aspect_id" => "all_aspects", :class => ("selected" if (!publisher_public && all_aspects_selected?(selected_aspects)))}
                  = t('all_aspects')

                - for aspect in all_aspects
                  = aspect_dropdown_list_item(aspect, !all_aspects_selected?(selected_aspects) && selected_aspects.include?(aspect) )

          = status.submit t('.share'), :disabled => publisher_hidden_text.blank?, :class => 'button creation', :tabindex => 2

          .facebox_content
            #question_mark_pane
              = render 'shared/public_explain'
    = link_to '', contacts_path(:aspect_ids => aspect_ids), :class => 'selected_contacts_link hidden'


    #publisher_photo_upload
      = render 'photos/new_photo', :aspect_ids => aspect_ids.join(',')

app/views/shared/_right_sections.html.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


- if AppConfig[:open_invitations]
  .section
    .title
      = image_tag('icons/plus.png')
      %h5
        = t('shared.invitations.invite_your_friends')
    .content
      = render "shared/invitations"

.section
  .title
    = image_tag('icons/heart.png')
    %h5
      = t('aspects.index.new_here.title')
  .content
    != t('aspects.index.new_here.follow', :link => link_to("#"+t('shared.publisher.new_user_prefill.newhere'), tag_path(:name => t('shared.publisher.new_user_prefill.newhere'))))
    %br
    = link_to(t('aspects.index.new_here.learn_more'), "https://github.com/diaspora/diaspora/wiki/Welcoming-Committee")

.section
  .title
    = image_tag('icons/question.png')
    %h5
      = t('aspects.index.help.need_help')
  .content
    = t('aspects.index.help.here_to_help')
    %br
    = t('aspects.index.help.do_you')
    %br
    != t('aspects.index.help.have_a_question', :link => link_to("#"+t('aspects.index.help.tag_question'), tag_path(:name => t('aspects.index.help.tag_question'))))
    %br
    != t('aspects.index.help.find_a_bug', :link => link_to("#"+t('aspects.index.help.tag_bug'), tag_path(:name => t('aspects.index.help.tag_bug'))))
    %br
    != t('aspects.index.help.feature_suggestion', :link => link_to("#"+t('aspects.index.help.tag_feature'), tag_path(:name => t('aspects.index.help.tag_feature'))))
    %br
    %br
    %p
      != t('aspects.index.help.tutorials_wiki_and_forum', :tutorial => link_to("Diasporial" , "http://diasporial.com/tutorials", :target => '_blank'), :wiki => link_to('Wiki','http://github.com/diaspora/diaspora/wiki', :target => '_blank'), :forum => link_to("Forum", "http://www.diasporaforum.org/", :target => '_blank'))
    %p
      != t('aspects.index.help.email_feedback', :link => link_to(t('aspects.index.help.email_link'), "mailto:feedback@joindiaspora.com"))

- unless AppConfig.configured_services.blank? || all_services_connected?
  .section
    .title
      = image_tag('icons/monotone_wrench_settings.png')
      %h5
        = t('aspects.index.services.heading')
    .content
      %div
        = t('aspects.index.services.content')

      #right_service_icons
        - AppConfig.configured_services.each do |service|
          - unless current_user.services.any?{|x| x.provider == service}
            = link_to(image_tag("social_media_logos/#{service.to_s.downcase}-24x24.png", :title => service.to_s.titleize), "/auth/#{service}")

.section
  .title
    = image_tag('icons/bookmark.png')
    %h5
      = t('bookmarklet.heading')
  .content
    != t('bookmarklet.explanation', :link => link_to(t('bookmarklet.post_something'), magic_bookmarklet_link))

.section
  .title
    = image_tag('icons/coffee.png')
    %h5
      = t('aspects.index.donate')
  .content
    - if AppConfig[:paypal_hosted_button_id].present?
      = t('aspects.index.keep_pod_running', :pod => URI.parse(AppConfig[:pod_url]).host)
      %br
      = render 'shared/donatepod'
    - else
      = t('aspects.index.keep_diaspora_running')
      %br
      = render 'shared/donatediaspora'

app/views/shared/_settings_nav.haml
%ul#settings_nav
  %li= link_to_unless_current t('profile'), edit_profile_path
  %li= link_to_unless_current t('account'), edit_user_path
  %li= link_to_unless_current t('privacy'), privacy_settings_path
  %li= link_to_unless_current t('_services'), services_path

app/views/shared/_stream.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

= render :partial => 'shared/stream_element',
         :collection => posts,
         :as => :post

app/views/shared/_stream_element.mobile.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.stream_element{:data=>{:guid=>post.id}}
  - if post.respond_to?(:nsfw?) && post.nsfw?
    .shield_wrapper
      .shield
        = t("javascripts.stream.nsfw")
        = link_to t('javascripts.stream.show'), '#'
  

  - if post.is_a?(Reshare)
    = render 'reshares/reshare', :reshare => post, :post => post.root

  = render 'shared/photo_area', :post => post

  .content
    = render 'shared/post_info', :post => post

    - if post.is_a?(StatusMessage)
      = render 'status_messages/status_message', :post => post, :photos => post.photos

  .bottom_bar
    .floater
      = mobile_reshare_icon(post)
      = mobile_comment_icon(post)
      = mobile_like_icon(post)

    != reactions_link(post)

    - if defined?(expanded_info) && expanded_info
      .comment_container
        .post_stats
          - if post.public?
            %span.comment_count
              = post.reshares.size

          %span.comment_count
            = post.comments.size

          %span.like_count
            = post.likes.size

        %ul.comments
          = render :partial => 'comments/comment', :collection => post.comments, :locals => {:post => post}

          %li.comment.add_comment_bottom_link_container
            = link_to t('comments.new_comment.comment'), new_post_comment_path(post), :class => 'add_comment_bottom_link btn comment_action inactive'